# Generated by Django 3.0.6 on 2020-09-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_image'),
        ),
    ]
