# Generated by Django 3.0.6 on 2020-09-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_detail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('message', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
        ),
    ]
