# Generated by Django 3.0.6 on 2020-09-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
