# Generated by Django 3.0.7 on 2020-09-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200912_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='', max_length=20),
        ),
    ]
