# Generated by Django 3.0.7 on 2020-09-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_project_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='role',
            new_name='date',
        ),
    ]
