# Generated by Django 3.0.7 on 2020-09-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20200913_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
