# Generated by Django 3.0.7 on 2020-09-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20200913_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
